### PR TITLE
add impactive models and fix dbt extractor

### PR DESCRIPTION
**Pull request by michaelefisher**
Here's the dbt after running:
```
  Format exported Airbyte dbt to CTA structure
```
and choosing `impactive` and `utils/config/` as the location of the extracted dbt

### CODE REVIEW

**Comment by emily-flambe** [comment]
> and choosing `impactive` and `utils/config/` as the location of the extracted dbt

Is this operating as intended? Looks like the new Impactive dbt files ended up in dbt-cta/impactive/models (which is where they should ultimately end up) - did you move the files there by hand?

**Review by emily-flambe — CHANGES_REQUESTED** [review]
Can we please modify the script so that the filenames for the CTA base models (in `1_cta_*`) have the `_base` suffix?

**Comment by emily-flambe** [comment]
> Can we please modify the script so that the filenames for the CTA base models (in `1_cta_*`) have the `_base` suffix?

Ope, I see now that this is a separate option one can select when firing up the script, `APPEND_BASE_TO_FILES`. Not a big deal, would be cute to automatically run that after extracting the dbt, but not a blocker to merging this in... thus I approve

**Review by emily-flambe — APPROVED** [review]
Can we please modify the script so that the filenames for the CTA base models (in `1_cta_*`) have the `_base` suffix?

^^ would be cute but not actually a blocker since there's a separate option for performing this step in the script

**Comment by michaelefisher** [comment]
@emily-flambe I didn't do anything by hand, I just chose the options that Jesus had already put together. This was ultimately just subbing out the actual extraction piece.

I don't think that changing the options for the script are in-scope here, I wasn't intending to touch any of the other script features that already exist. Just getting it to parity.

**Comment by michaelefisher** [comment]
Lol ok @emily-flambe I can see why you were asking about where the files went. This was deleting them:

https://github.com/community-tech-alliance/dbt-cta/pull/252/files#diff-7107c0b9edf473b2867bdfdb196193ccdf2d9644c28d35acacc554bfc9409c81L19

Whoops.

**Review by emily-flambe — APPROVED** [review]

**Pull request merged**
