### PR TITLE
[DE-328] Join DAG metadata

### PR DESCRIPTION
**Pull request by jackwelty**
This PR joins in a series of metadata sources to cobble together a complete picture of which syncs are associated with each DAG, which partner is associated with each sync, and which syncs we care about monitoring.

We pull this metadata from three sources:
1. A [Google Sheet](https://docs.google.com/spreadsheets/d/13xNwLfmT8frlqnPrqKVM1-YH00yRakoK1wRcXDOMjuc/edit#gid=0) of non-Airbyte/dbt syncs, created by @emily-flambe, and accessed in BQ via an external table
2. A [Google Sheet](https://docs.google.com/spreadsheets/d/1drlo-3lWRFOkFlXqDXW9EPqpRNhRMA2uNR7X_6647RY/edit#gid=0) of dag IDs we don't care about monitoring (this was added so we can keep dag IDs out of code). This is also accessed in BQ via an external table.
3. Some parsed json from our DAG config files in `airflow-dags`. This parsing and uploading to GCS is added in [this PR](https://github.com/community-tech-alliance/airflow-dags/pull/277). This data is also accessed in BQ via an external table.

We join all of these sources into our monitoring dbt project, and end up with a unioned view of sync runs and their associated partners. We are also allowing for a bit of nullness on sync and partner names to give folks time to update these metadata sources.

This PR also adds the [dbt_external_tables](https://github.com/dbt-labs/dbt-external-tables) package to help create/refresh external tables.

TODO (post-merge):
 - [ ] Update dbt dependencies in prod/dev
 - [x] Share Composer service accounts on Sheets
 - [x] Create external table in prod from json catalog uploaded in https://github.com/community-tech-alliance/airflow-dags/pull/277
 - [ ] Create sheets-backed external tables in prod by running `dbt run-operation stage_external_sources -t cta`

### CODE REVIEW

**Review by emily-flambe — APPROVED** [review]
Wow wow wowowow no notes from me, this is exquisite!! Maybe a dumb q, but if you used dbt to create the external tables, how did dbt have access to them?

I'm in shambles that I never knew you could use external tables this way 🤯 

What are next steps to get the beautiful merged data to appear on the dash?

**Comment by jackwelty** [comment]
> Wow wow wowowow no notes from me, this is exquisite!! Maybe a dumb q, but if you used dbt to create the external tables, how did dbt have access to them?
> 
> I'm in shambles that I never knew you could use external tables this way 🤯
> 
> What are next steps to get the beautiful merged data to appear on the dash?

great q that I just sorted out when running in `dev`! Running locally--as long as the user has access to the sheet we're gtg. When we deploy, we just have to share the Composer service accounts (`composer@[project_id].iam.gserviceaccount.com`) on the document.

**Review by jitoquinto — APPROVED** [review]
woah this is really cool!!

**Comment by kanelouise** [comment]
que fancy!

**Comment by emily-flambe** [comment]
> > Wow wow wowowow no notes from me, this is exquisite!! Maybe a dumb q, but if you used dbt to create the external tables, how did dbt have access to them?
> > I'm in shambles that I never knew you could use external tables this way 🤯
> > What are next steps to get the beautiful merged data to appear on the dash?
> 
> great q that I just sorted out when running in `dev`! Running locally--as long as the user has access to the sheet we're gtg. When we deploy, we just have to share the Composer service accounts (`composer@[project_id].iam.gserviceaccount.com`) on the document.

Ah! Hence the TODO you listed in the PR description. It's all coming together ✨

**Pull request merged**
