### PR TITLE
adding yaml def and dbt tests for action_network full_refresh

### PR DESCRIPTION
**Pull request by royconst**
Generated a models yaml file and added some appropriate tests to fields like `id` and `_airbyte_*_hasid`.

### CODE REVIEW

**Review by kanelouise — APPROVED** [review]
PHEW what a long one! LGTM 👍

**Comment by emily-flambe** [comment]
yeah wow you know it's a good time when Github won't load the diff for the only file added by the PR lol. @royconst can you confirm that these tests pass when running dbt locally?

**Comment by royconst** [comment]
Yes, can confirm. 960 tests all passed. @emily-flambe

**Review by emily-flambe — APPROVED** [review]
Then let's ship it :shipit: !!!

**Pull request merged**
