### PR TITLE
feat: add dbt models for Spoke (Rewired flavor)

### PR DESCRIPTION
**Pull request by emily-flambe**
Related JIRA tickets:

Phase 1 sync - [DE-18](https://techallies.atlassian.net/browse/DE-18) (see also [PR 146 in airflow-dags](https://github.com/community-tech-alliance/airflow-dags/pull/146))
Phase 2 sync - [DE-68](https://techallies.atlassian.net/browse/DE-68) (closed by this PR, once deployed and merged etc)

[DE-18]: https://techallies.atlassian.net/browse/DE-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DE-68]: https://techallies.atlassian.net/browse/DE-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jitoquinto — APPROVED** [review]

**Comment by emily-flambe** [comment]
@jitoquinto do you know if we are able to make Draft PRs in this repo? I don't see a way to make this a draft 🤔

**Comment by jitoquinto** [comment]
> @jitoquinto do you know if we are able to make Draft PRs in this repo? I don't see a way to make this a draft 🤔

Hmmm do we need to flip a switch anywhere in settings?? Im seeing this up top though?
image

**Comment by emily-flambe** [comment]
ok @jitoquinto I'm actually a little stumped about this - the sql files in `2_partner_matviews` seem pretty straightforward, but I'm hitting a bunch of this error: 

```
Resource dev3869c056:spoke_sua did not meet condition IF_MATCH
```

I've tried googling that error but can't figure out what it means... is it something about how the dataset itself is configured? I'll tinker more later today but curious if you have any thoughts 🧐

**Comment by emily-flambe** [comment]
arrrrgh @jitoquinto I really wanted to get this working before I went OOO but I'm hitting new errors I don't understand - see for example this task run, most of the `1_cta_base` tables are being updated just fine, but some of them throw an error about the partitioning field changing, which I have never seen before and don't understand 😭 so I'll have to push this ticket to the next sprint. If you have any time (in your capacity as proglead?) to investigate, that would be super 🙏 I really don't know why it has been so hard to just materialize these dang tables into the partner project. Maybe I should skip the `_base` step entirely? The so-called "_raw" tables should be fine to materialize directly. Maybe I'll try that later tonight...

**Comment by emily-flambe** [comment]
> arrrrgh @jitoquinto I really wanted to get this working before I went OOO but I'm hitting new errors I don't understand - see for example [this task run](https://256d9e043bf64c2d9fda5c645b99c062-dot-us-central1.composer.googleusercontent.com/log?dag_id=TEMP_spoke_sua_dbt_dag&task_id=dbt_run_cta&execution_date=2023-02-13T23%3A31%3A43.755090%2B00%3A00), most of the `1_cta_base` tables are being updated just fine, but some of them throw an error about the partitioning field changing, which I have never seen before and don't understand 😭 so I'll have to push this ticket to the next sprint. If you have any time (in your capacity as proglead?) to investigate, that would be super 🙏 I really don't know why it has been so hard to just materialize these dang tables into the partner project. Maybe I should skip the `_base` step entirely? The so-called "_raw" tables should be fine to materialize directly. Maybe I'll try that later tonight...

ok I reflected deeply and have decided we should just materialize the partner views directly from the "_raw" tables - this should be fine, but we can figure out how to finesse it later if necessary

**Comment by jitoquinto** [comment]
> > arrrrgh @jitoquinto I really wanted to get this working before I went OOO but I'm hitting new errors I don't understand - see for example [this task run](https://256d9e043bf64c2d9fda5c645b99c062-dot-us-central1.composer.googleusercontent.com/log?dag_id=TEMP_spoke_sua_dbt_dag&task_id=dbt_run_cta&execution_date=2023-02-13T23%3A31%3A43.755090%2B00%3A00), most of the `1_cta_base` tables are being updated just fine, but some of them throw an error about the partitioning field changing, which I have never seen before and don't understand 😭 so I'll have to push this ticket to the next sprint. If you have any time (in your capacity as proglead?) to investigate, that would be super 🙏 I really don't know why it has been so hard to just materialize these dang tables into the partner project. Maybe I should skip the `_base` step entirely? The so-called "_raw" tables should be fine to materialize directly. Maybe I'll try that later tonight...
> 
> ok I reflected deeply and have decided we should just materialize the partner views directly from the "_raw" tables - this should be fine, but we can figure out how to finesse it later if necessary

🙃 dbt can never just be easy. But yeah i can look into this if it still needs looking into?

**Comment by emily-flambe** [comment]
> > > arrrrgh @jitoquinto I really wanted to get this working before I went OOO but I'm hitting new errors I don't understand - see for example [this task run](https://256d9e043bf64c2d9fda5c645b99c062-dot-us-central1.composer.googleusercontent.com/log?dag_id=TEMP_spoke_sua_dbt_dag&task_id=dbt_run_cta&execution_date=2023-02-13T23%3A31%3A43.755090%2B00%3A00), most of the `1_cta_base` tables are being updated just fine, but some of them throw an error about the partitioning field changing, which I have never seen before and don't understand 😭 so I'll have to push this ticket to the next sprint. If you have any time (in your capacity as proglead?) to investigate, that would be super 🙏 I really don't know why it has been so hard to just materialize these dang tables into the partner project. Maybe I should skip the `_base` step entirely? The so-called "_raw" tables should be fine to materialize directly. Maybe I'll try that later tonight...
> > 
> > 
> > ok I reflected deeply and have decided we should just materialize the partner views directly from the "_raw" tables - this should be fine, but we can figure out how to finesse it later if necessary
> 
> 🙃 dbt can never just be easy. But yeah i can look into this if it still needs looking into?

haha, I know right?? No need to do any deep investigation here - we can revisit if it turns out there's an Important Reason to create _base tables in the CTA project. 😎

**Review by jitoquinto — APPROVED** [review]

**Pull request merged**
