### PR TITLE
Kane/de 153 moveon spoke dbt

### PR DESCRIPTION
**Pull request by kanelouise**
[DE-153](https://techallies.atlassian.net/browse/DE-153) dbt

[DE-153]: https://techallies.atlassian.net/browse/DE-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kanelouise** [comment]
I cannot replicate  [this error](https://3f8a7223f9814e7ea9c19691ea09fb69-dot-us-central1.composer.googleusercontent.com/log?dag_id=spoke_mo&task_id=spoke_mo_partner_a.partner_a_transforms.0_partner_a_test_db_transforms.0_partner_a_0_dbt_run_cta&execution_date=2023-06-23T22%3A24%3A13.928097%2B00%3A00) locally that's appearing in Composer. locally the things are running fine and without errors. i checked the GCS buckets for extra or erroneous files and didn't find any. do you have any thoughts about where i might go next @emily-flambe?

**Review by emily-flambe — CHANGES_REQUESTED** [review]
@kanelouise can we also include `_airbyte_emitted_at` in the partner materialized view models? Once that's in there I say this is good to merge!

(I assume you used the helper script to generate the matviews - [This PR](https://github.com/community-tech-alliance/dbt-cta/pull/183) was supposed to make it so the helper script includes `_airbyte_emitted_at` when generating them, but that PR probably got merged after this branch was created)

**Comment by kanelouise** [comment]
> @kanelouise can we also include `_airbyte_emitted_at` in the partner materialized view models? Once that's in there I say this is good to merge!
> 
> (I assume you used the helper script to generate the matviews - [This PR](https://github.com/community-tech-alliance/dbt-cta/pull/183) was supposed to make it so the helper script includes `_airbyte_emitted_at` when generating them, but that PR probably got merged after this branch was created)

ah drats. thanks for pointing out, @emily-flambe. does this mean i need to re-run the helper script?

**Comment by emily-flambe** [comment]
> > @kanelouise can we also include `_airbyte_emitted_at` in the partner materialized view models? Once that's in there I say this is good to merge!
> > (I assume you used the helper script to generate the matviews - [This PR](https://github.com/community-tech-alliance/dbt-cta/pull/183) was supposed to make it so the helper script includes `_airbyte_emitted_at` when generating them, but that PR probably got merged after this branch was created)
> 
> ah drats. thanks for pointing out, @emily-flambe. does this mean i need to re-run the helper script?

you can probably do a bulk find-and-replace on all files in the folder (I can do that in TextEdit but I assume it's possible in all IDEs) to slap `_airbyte_emitted_at` into the matview models! But if that turns out to be annoying, you could also just merge `main` into your branch and rerun the helper script. Whatever is easier for you and gets the job done 😎

**Comment by kanelouise** [comment]
@emily-flambe, i want to understand what's missing conceptually here. i used Blocks as a model and simply added `_airbyte_emitted_at` to the `_ab3` files and the files in `partner_matviews` and expected that to add `_airbyte_emitted_at` to the matviews themselves. Then I ran my dbt locally and expected to see the `airbyte_emitted_at` fields in the partner view. 

However, looking at the [partner view of the `zip_code` table](https://console.cloud.google.com/bigquery?project=dev3869c056&supportedpurview=project&ws=!1m35!1m4!4m3!1sprod-partner-a-176bffe6!2smospoke_test_db!3scampaign!1m4!4m3!1sprod-partner-a-176bffe6!2smospoke_test_db!3sassignment!1m4!4m3!1sprod8b61f23e!2smospoke_test_db!3sassignment_base!1m4!1m3!1sdev3869c056!2sbquxjob_333c0ffe_1892cbd733e!3sUS!1m4!4m3!1sprod-partner-a-176bffe6!2smospoke_test_db!3szip_code!1m4!1m3!1sdev3869c056!2sbquxjob_21ae14e4_1892cd23458!3sUS!1m4!1m3!1sdev3869c056!2sbquxjob_5dd44dea_1892ce093d9!3sUS) (because it is a full refresh so should populate the field even if there's not new data), there isn't the `_airbyte_emitted_at` field. Even when I ran it as `SELECT * from zip_code_base`. I know I can just regenerate the views with the helper script, but I'd really like to have a deep understanding of what's happening under the hood, or what else I'm missing here.

**Comment by emily-flambe** [comment]
> @emily-flambe, i want to understand what's missing conceptually here. i used Blocks as a model and simply added `_airbyte_emitted_at` to the `_ab3` files and the files in `partner_matviews` and expected that to add `_airbyte_emitted_at` to the matviews themselves. Then I ran my dbt locally and expected to see the `airbyte_emitted_at` fields in the partner view.
> 
> However, looking at the [partner view of the `zip_code` table](https://console.cloud.google.com/bigquery?project=dev3869c056&supportedpurview=project&ws=!1m35!1m4!4m3!1sprod-partner-a-176bffe6!2smospoke_test_db!3scampaign!1m4!4m3!1sprod-partner-a-176bffe6!2smospoke_test_db!3sassignment!1m4!4m3!1sprod8b61f23e!2smospoke_test_db!3sassignment_base!1m4!1m3!1sdev3869c056!2sbquxjob_333c0ffe_1892cbd733e!3sUS!1m4!4m3!1sprod-partner-a-176bffe6!2smospoke_test_db!3szip_code!1m4!1m3!1sdev3869c056!2sbquxjob_21ae14e4_1892cd23458!3sUS!1m4!1m3!1sdev3869c056!2sbquxjob_5dd44dea_1892ce093d9!3sUS) (because it is a full refresh so should populate the field even if there's not new data), there isn't the `_airbyte_emitted_at` field. Even when I ran it as `SELECT * from zip_code_base`. I know I can just regenerate the views with the helper script, but I'd really like to have a deep understanding of what's happening under the hood, or what else I'm missing here.

Ahh!! So, and this is not well documented at all (you would only know if you'd squinted very hard at line 31 of the [cacher script](https://snippets.cacher.io/snippet/1db187592eb6ab37ab0b) with the commands for running dbt locally) - when you alter the schema of a partner materialized view (for example by adding a column), the matview needs to be built by running the dbt with `--full-refresh`, like:

```pipenv run dbt run --target partner --select tag:partner --full-refresh```

I just ran that on `mospoke_test_db` and the matviews seem to have `_airbyte_emitted_at` now!

I realize this is both very poorly documented and a somewhat critical piece of DE knowledge, so very open to ideas about how to make this less mysterious going forward 👀

**Comment by kanelouise** [comment]
> 

thanks, @emily-flambe! This illuminates the same sticking point I was encountering in your dbt presentation yesterday at Eng Weekly. Because `full refresh` means something very different in Airbyte, I was confused why we'd run an `incremental` sync with the `full refresh` tag. The answer is that the same phrase means two different things in these two lil data worlds. 

As for your question: how do we make this more knowledge more accessible? I could see there being value in adding it to the [Running dbt locally](https://docs.google.com/document/d/15vnifQ951gWAkhhjr-2aIhkqjk8QMhF6lqerMCqgJwA/edit#heading=h.oy78phylv5s7) doc. Especially because, as you were saying yesterday in Eng Weekly, this may be a fix that a prog lead may encounter someday and that'd be a handy doc for prog leads everywhere.

**Comment by kanelouise** [comment]
Once this has your sign-off, it'll be good to merge, @emily-flambe.

**Review by emily-flambe — APPROVED** [review]

**Pull request merged**
