### PR TITLE
[DE-289] Add run-level messages

### PR DESCRIPTION
**Pull request by jackwelty**
This PR creates an `error_message` field in our final reporting table, and surfaces that field in a new viz component on the "Run Listing" page of our PHD ([live in dev](https://lookerstudio.google.com/s/n5BG9nkK1Sg)).

Elementary gives us the dbt error log for every failed invocation, so we just `string_agg()` those together with the model name, and stick all of that in a long string `error_message` field. "Real" debugging should probably take place via Airflow (and we provide all the necessary DAG/run IDs) for this, but this is a quick way for users to get a glimpse at what went wrong for a given run.

### CODE REVIEW

**Comment by emily-flambe** [comment]
woo!! do we have this running in dev PHD yet?

**Comment by jackwelty** [comment]
> 

we do! https://lookerstudio.google.com/s/n5BG9nkK1Sg

**Comment by jackwelty** [comment]
> > > woo!! do we have this running in dev PHD yet?
> > 
> > 
> > we do! https://lookerstudio.google.com/s/n5BG9nkK1Sg
> 
> Ooh!! um sorry if I am being dense but where can I see the error messages in the PHD?

not dense! The "Run Listing" page, click a row in the table to view the error message below

**Comment by emily-flambe** [comment]
> > > > woo!! do we have this running in dev PHD yet?
> > > 
> > > 
> > > we do! https://lookerstudio.google.com/s/n5BG9nkK1Sg
> > 
> > 
> > Ooh!! um sorry if I am being dense but where can I see the error messages in the PHD?
> 
> not dense! The "Run Listing" page, click a row in the table to view the error message below

OMG exquisite. Got a couple requests that I'll put in JIRA, good to merge this PR!

**Review by emily-flambe — APPROVED** [review]

**Pull request merged**
