### PR TITLE
style: format action builder

### PR DESCRIPTION
**Pull request by jitoquinto**
Ran SQLFluff on Action Builder! The only changes im seeing on here are 
- Remove unused table aliases
- Add `as` keyword when declaring an alias
- remove empty lines at end of file

There were some other linting errors that were all of this kind:
``` Keywords should not be used as identifiers.```
But they were column existing column names that we probably shouldn't change, so i left it as is.

### CODE REVIEW

**Review by kanelouise — COMMENTED** [review]
seems cool! i have the same q here as the other `sqlfluff` PR you have open right now: does dbt run without a problem without the extra line at the end of each file?

**Comment by jitoquinto** [comment]
> seems cool! i have the same q here as the other `sqlfluff` PR you have open right now: does dbt run without a problem without the extra line at the end of each file?

same here! ran the models and it ran through successfully
image

**Review by kanelouise — APPROVED** [review]
nice! glad the dbt runs!

**Review by emily-flambe — APPROVED** [review]
FLUFF ALL THE THINGS. And yeah sqlfluff is gonna have to accept that we have keywords as column names sometimes and that's just the world we live in

**Pull request merged**
