### PR TITLE
feat: new script for generating _ab4 deduping CTEs

### PR DESCRIPTION
**Pull request by emily-flambe**
This PR adds a quick and dirty script that iterates through the tables in a project (determined via user input) and generates `0_ctes/TABLE_ab4.sql` files that dedupe rows using the `_hashid` field in each table.

Because this is quick and dirty, the script hardcodes the template being used to generate the SQL, and assumes that the desired filename has the suffix `_ab4`. This should be fine for most or all of our syncs that still do not have these CTEs included, and the main purpose of this script is to facilitate adding those models to existing projects. Future syncs will use `generate_dbt.py` to generate dbt models, and that script already creates deduping CTEs, so this script will no longer be useful once all existing projects have had these models added.

### CODE REVIEW

**Review by kanelouise — APPROVED** [review]
LGTM!

**Review by kanelouise — COMMENTED** [review]
Ooo, I guess we could add a loop for updating the base tables as well?

**Comment by emily-flambe** [comment]
> Ooo, I guess we could add a loop for updating the base tables as well?

oh that's a good idea! bet that would be easy, I'll ask chatgpt to throw that in there lol

**Review by kanelouise — COMMENTED** [review]
Cool, love the base tables addition.

**Pull request merged**
